set -x

export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="/mnt/bn/tiktok-mm-4/aiic/users/dingyang/data/projudge/rl_train.yaml" \
    data.val_files="/mnt/bn/tiktok-mm-4/aiic/users/dingyang/data/yamls/mv_math_rl_val.yaml" \
    data.train_batch_size=256 \
    data.max_prompt_length=8192 \
    data.max_response_length=2048 \
    data.image_key=images \
    reward_model.reward_manager=custom@mv_math \
    'data.post_prompt="\nOutput the thinking process within <think> </think> tags and final answer within <answer> </answer> tags. The final answer should contain \\boxed{{}}."' \
    actor_rollout_ref.model.path=/mnt/bn/tiktok-mm-4/aiic/users/dingyang/models/Qwen2.5-VL-7B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_scheduler=constant \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.n=8 \
    'actor_rollout_ref.rollout.limit_mm_per_prompt={'image': 10}' \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.0 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='dingyang_verl_grpo_projudge_debug' \
    trainer.experiment_name='qwen2_5_vl_7b_projudge_0.05format_rollout8' \
    trainer.log_training_rollouts_freq=10 \
    trainer.train_generations_to_log_to_wandb=256 \
    trainer.val_generations_to_log_to_wandb=128 \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.total_epochs=5 \
    reward_model.log_rewards_separately=True \
    reward_model.acc_reward_weight=0.95 \
    reward_model.format_reward_weight=0.05 \
    trainer.reflection_keywords=['wait,recheck,alternatively,retry,however,rethink,re-evaluate,hmm,re-check,double-check'] \
    # 'trainer.default_local_dir=/mnt/hdfs/yangding/checkpoints/${trainer.project_name}/${trainer.experiment_name}'