### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 100352
video_max_pixels: 100352
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json
# pure_bf16: true

### dataset
dataset: sftdataset
template: qwen2_vl
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: checkpoints
logging_steps: 1
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: null  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.10
bf16: true
ddp_timeout: 180000000
flash_attn: fa2

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500